Test Release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,112 +2,184 @@ version: 2.1
 jobs:
   build:
     docker:
-      - image: fr3akyphantom/alpine-docker-runner:latest
+      - image: fr3akyphantom/droid-runner:latest
     environment:
       MANIFEST_BRANCH: 'android-10.0'
-      VERSION: '2.9.1-test'
+      VERSION: '2.9.2-test'
       MAINTAINER: "PBRP Team"
       VENDOR: 'xiaomi'
       CODENAME: 'whyred'
       FLAVOR: 'eng'
       TEST_BUILD: 'true'
+      PB_ENGLISH: 'true'
       CHANGELOG: "Initial Build"
-    working_directory: /home/builder/pitchblack
+      EXTRA_CMD: "rm -f device/${VENDOR}/${CODENAME}/recovery/root/sbin/*.so"
+    working_directory: /home/builder
     steps:
-      - setup_remote_docker:
-          version: 19.03.8
-      #- run:
-          #name: Create Docker volumes
-          #command: |
-            #docker create --name input --volume /home/builder/base alpine:3.12 /bin/true
-            #docker cp . input:/home/builder/base/
-            #docker create --name output --volume /home/builder/pitchblack alpine:3.12 /bin/true
-            #docker cp build.sh output:/home/builder/pitchblack/
       - run:
+          name: CREATE KEEP-ALIVE SHELL
           command: |
-            echo -e "Available CPU Threads - " && nproc --all
-            [ ! -d /home/builder/.ccache ] && mkdir -p /home/builder/.ccache
-            docker pull fr3akyphantom/droid-builder:focal
-            docker run --privileged --rm -i \
-              -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) \
-              -e GitHubMail=${GitHubMail} \
-              -e GitHubName=${GitHubName} \
-              -e GITHUB_TOKEN=${GITHUB_TOKEN} \
-              -e CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME} \
-              -e CIRCLE_PROJECT_REPONAME=${CIRCLE_PROJECT_REPONAME} \
-              -e CIRCLE_BRANCH=${CIRCLE_BRANCH} \
-              -e CIRCLE_SHA1=${CIRCLE_SHA1} \
-              -e MANIFEST_BRANCH=${MANIFEST_BRANCH} \
-              -e VERSION=${VERSION} \
-              -e MAINTAINER="${MAINTAINER}" \
-              -e VENDOR=${VENDOR} \
-              -e CODENAME=${CODENAME} \
-              -e FLAVOR=${FLAVOR} \
-              -e TEST_BUILD=${TEST_BUILD} \
-              -e CHANGELOG="${CHANGELOG}" \
-              -v "/home/builder/pitchblack:/home/builder/pitchblack/:rw,z" \
-              -v "/home/builder/.ccache:/srv/ccache:rw" \
-              fr3akyphantom/droid-builder:focal bash \<< EOF
-            
-            DIR=$(pwd) && echo -e "Current Path is - " && echo ${DIR}
-            
-            JAVA_OPTS=${JAVA_OPTS:+" -Xmx8G "}
-            
+            while true; do
+              echo "" && sleep 480
+            done
+          background: true
+      - run:
+          name: SANITY CHECKS
+          command: |
+            # SANITY CHECKS
+            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
+            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
+            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
+            if [[ -z $MANIFEST_BRANCH ]]; then echo -e "You haven't configured PitchBlack Recovery Project Manifest Branch." && exit 1; fi
+            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
+            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
+            if [[ -z $BUILD_LUNCH ]] && [[ -z $FLAVOR ]]; then echo -e "Set at least one variable. BUILD_LUNCH or FLAVOR." && exit 1; fi
+
             # Set GitAuth Infos"
             git config --global user.email $GitHubMail
             git config --global user.name $GitHubName
             git config --global credential.helper store
             git config --global color.ui true
             
+            # Use Google Git Cookies for Smooth repo-sync
             git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
             bash google-git-cookies/setup_cookies.sh
             rm -rf google-git-cookies
-            
-            echo -e "Starting the CI Build Process...\n"
-            
-            cd ${DIR} && mkdir android && cd android
+      - run:
+          name: REPO SYNC
+          command: |
+            cd /home/builder/
+
+            mkdir repository && cd repository
 
             echo -e "Initializing PBRP repo sync..."
-            repo init -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth=1
-            time repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
+            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
+            time repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
             
-            rm -rf vendor/pb && git clone --depth 1 https://github.com/PitchBlackRecoveryProject/vendor_pb.git -b "pb-10.0" vendor/pb
+            rm -rf development/apps/ development/samples/ packages/apps/
+
+            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 --depth 1 vendor/pb
             rm vendor/pb/vendorsetup.sh
+
+            echo -e "\nGetting the Device Tree on place"
+            if [[ "${CIRCLE_PROJECT_USERNAME}" == "PitchBlackRecoveryProject" ]]; then
+                git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
+            else
+                git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
+            fi
+
+            if [[ -n ${USE_SECRET_BOOTABLE} ]]; then
+                [[ -n ${PBRP_BRANCH} ]] && unset PBRP_BRANCH
+                [[ -z ${SECRET_BR} ]] && SECRET_BR="android-9.0"
+                rm -rf bootable/recovery
+                git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/pbrp_recovery_secrets -b ${SECRET_BR} --single-branch bootable/recovery
+            elif [[ -n ${PBRP_BRANCH} ]]; then
+                rm -rf bootable/recovery
+                git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${PBRP_BRANCH} --single-branch bootable/recovery
+            fi      
+      - run:
+          name: EXPORT ENVS
+          command: |
+            cd /home/builder/
+            printenv | sort -h > environ.txt
+            grep environ.txt -e GitHubMail -e GitHubName -e GITHUB_TOKEN \
+              -e CIRCLE_PROJECT_USERNAME -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BRANCH -e CIRCLE_SHA1 \
+              -e MANIFEST_BRANCH -e USE_SECRET_BOOTABLE -e SECRET_BR -e PBRP_BRANCH \
+              -e VERSION -e MAINTAINER -e VENDOR -e CODENAME -e FLAVOR -e BUILD_LUNCH \
+              -e TEST_BUILD -e PB_OFFICIAL -e EXTRA_CMD -e PB_ENGLISH -e CHANGELOG \
+              > environments.file
+            rm environ.txt
+      - setup_remote_docker:
+          version: 19.03.8
+      - run:
+          name: COPY TO DOCKER REMOTE
+          command: |
+            cd /home/builder/repository/
+            ls -lA .
+            docker pull fr3akyphantom/droid-builder:focal
+            docker create --name workstation --volume /home/builder/android fr3akyphantom/droid-builder:focal bash
+            docker cp . -a -L workstation:/home/builder/android/
+            if [[ "$?" = "0" ]]; then
+              echo -e "Successfully Copied onto Remote Container"
+              rm -rf *
+            fi
+            [[ -f /home/builder/.gitconfig ]] && docker cp /home/builder/.gitconfig -a -L workstation:/home/builder/
+            [[ -f /home/builder/.gitcookies ]] && docker cp /home/builder/.gitcookies -a -L workstation:/home/builder/
+            [[ -f /home/builder/.git-credentials ]] && docker cp /home/builder/.git-credentials -a -L workstation:/home/builder/
+      - run:
+          command: |
+            [ ! -d /home/builder/.ccache ] && mkdir -p /home/builder/.ccache
+            cd /home/builder
+            mkdir android && cd android
+            docker run --privileged -it --name worker \
+              --user builder -e USER_ID=1000 -e GROUP_ID=1000 \
+              --env-file "/home/builder/environments.file" \
+              --volumes-from workstation \
+              -v "/home/builder/:/home/builder/:rw,z" \
+              -v "${pwd}:/home/builder/android/:rw,z" \
+              -v "/home/builder/.ccache:/srv/ccache:rw" \
+              --workdir /home/builder \
+              fr3akyphantom/droid-builder:focal bash \<< EOF
+            
+            cd /home/builder/android/
+            ls -lA .
+            
+            if [[ -n $EXTRA_CMD ]]; then
+              eval "$EXTRA_CMD"
+              cd /home/builder/android/
+            fi
+            
+            JAVA_OPTS=${JAVA_OPTS:+" -Xmx8G "}
+            
+            echo -en "Current Username is - " && whoami
+            
+            THREADCOUNT=$(nproc --all)
+            echo -en "Available CPU Threads - " && echo ${THREADCOUNT}
             
             echo -e "\nGetting the Device Tree on place"
             git clone https://$GITHUB_TOKEN@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} --depth 1 device/${VENDOR}/${CODENAME}
-            
-            du -sh * | sort -h
-            du -sh .repo
-            rm -f device/${VENDOR}/${CODENAME}/recovery/root/sbin/*.so
-            rm -rf development/apps/ development/samples/ packages/apps/
-            du -sh * | sort -h
-            
+
             echo -e "\nPreparing Delicious Lunch..."
             export ALLOW_MISSING_DEPENDENCIES=true
             source build/envsetup.sh
-            lunch omni_${CODENAME}-${FLAVOR}
+            if [[ -n $BUILD_LUNCH ]]; then
+              lunch ${BUILD_LUNCH}
+            elif [[ -n $FLAVOR ]]; then
+              lunch omni_${CODENAME}-${FLAVOR}
+            fi
             
-            mka recoveryimage
+            if [[ ${THREADCOUNT} -gt 8 ]]; then MAKEJOB=${THREADCOUNT}
+            elif [[ ${THREADCOUNT} -gt 4 && ${THREADCOUNT} -lt 8 ]]; then MAKEJOB=8
+            elif [[ ${THREADCOUNT} -eq 4 ]]; then MAKEJOB=${THREADCOUNT}
+            elif [[ ${THREADCOUNT} -eq 2 ]]; then MAKEJOB=4
+            fi
+            
+            make -j${MAKEJOB} recoveryimage
             echo -e "\nYummy Recovery is Served.\n"
             
-            echo -e "Total Number of CPU Threads Used - " && nproc --all
+            EOF
+      - run:
+          name: COPY TO PRIMARY AND RELEASE
+          comand: |
+            cd /home/builder/
             
-            cd ${DIR}/android
-            mkdir upload
+            mkdir -p {fetch,upload}
+            cd /home/builder/fetch/
+            
+            docker cp -a -L worker:/home/builder/android/out/target/product/${CODENAME}/* .
             
             echo "Ready to Deploy"
-            export TEST_BUILDFILE="out/target/product/${CODENAME}/PitchBlack*-UNOFFICIAL.zip"
-            export TEST_BUILDIMG="out/target/product/${CODENAME}/recovery.img"
+            export TEST_BUILDFILE=$(find $(pwd)/PitchBlack*-UNOFFICIAL.zip 2>/dev/null)
+            export TEST_BUILDIMG=$(find $(pwd)/recovery.img 2>/dev/null)
+            
+            cd /home/builder/
 
             echo "Got the Unofficial Build: $TEST_BUILDFILE"
-            cp ${TEST_BUILDFILE} ${TEST_BUILDFILE} ${DIR}/upload/
+            cp ${TEST_BUILDFILE} ${TEST_BUILDIMG} /home/builder/upload
             # release
-            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Release for $(echo $CODENAME)" -b "PBRP $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION}-test ${DIR}/upload
+            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Release for $(echo $CODENAME)" -b "PBRP $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION}-test /home/builder/upload
             
             echo -e "\n\nAll Done Gracefully\n\n"
-            EOF
-          name: AIO Build
 
 workflows:
   version: 2
