Full Remote

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,58 +29,8 @@ jobs:
             EOF
             chmod a+x /tmp/act.sh
       - run:
-          name: "SANITY CHECKS & GIT SETUP"
-          command: |
-            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
-            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
-            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
-            if [[ -z $MANIFEST_BRANCH ]]; then echo -e "You haven't configured PitchBlack Recovery Project Manifest Branch." && exit 1; fi
-            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
-            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
-            if [[ -z $BUILD_LUNCH ]] && [[ -z $FLAVOR ]]; then echo -e "Set at least one variable. BUILD_LUNCH or FLAVOR." && exit 1; fi
-            # Set GitAuth Infos"
-            git config --global user.email $GitHubMail
-            git config --global user.name $GitHubName
-            git config --global credential.helper store
-            git config --global color.ui true
-            # Use Google Git Cookies for Smooth repo-sync
-            git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
-            bash google-git-cookies/setup_cookies.sh
-            rm -rf google-git-cookies
-      - run:
-          name: "REPO SYNC"
-          command: |
-            cd /home/builder/
-            mkdir repository && cd repository
-            echo -e "Initializing PBRP repo sync..."
-            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
-            /tmp/act.sh & repo sync -c -q --force-sync --no-clone-bundle --no-tags -j$(nproc --all)
-            rm -rf development/apps/ development/samples/ packages/apps/
-            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 --depth 1 vendor/pb
-            rm vendor/pb/vendorsetup.sh
-            echo -e "\nGetting the Device Tree on place"
-            if [[ "${CIRCLE_PROJECT_USERNAME}" == "PitchBlackRecoveryProject" ]]; then
-              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
-            else
-              git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
-            fi
-            if [[ -n ${USE_SECRET_BOOTABLE} ]]; then
-              [[ -n ${PBRP_BRANCH} ]] && unset PBRP_BRANCH
-              [[ -z ${SECRET_BR} ]] && SECRET_BR="android-9.0"
-              rm -rf bootable/recovery
-              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/pbrp_recovery_secrets -b ${SECRET_BR} --single-branch bootable/recovery
-            elif [[ -n ${PBRP_BRANCH} ]]; then
-              rm -rf bootable/recovery
-              git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${PBRP_BRANCH} --single-branch bootable/recovery
-            fi
-            ls -lA .
-            echo -en "act-shell pid number is - " && cat /tmp/act.pid
-            ACTPID=$(cat /tmp/act.pid) && kill -s SIGTERM ${ACTPID}
-      - run:
           name: "EXPORT ENVS"
           command: |
-            cd /home/builder/
-            ls -lA .
             printenv | sort -h > environ.txt
             grep environ.txt -e GitHubMail -e GitHubName -e GITHUB_TOKEN \
               -e CIRCLE_PROJECT_USERNAME -e CIRCLE_PROJECT_REPONAME -e CIRCLE_BRANCH -e CIRCLE_SHA1 \
@@ -93,25 +43,7 @@ jobs:
       - setup_remote_docker:
           version: 19.03.8
       - run:
-          name: "COPY TO DOCKER REMOTE"
-          command: |
-            cd /home/builder/repository/
-            du -sh .repo && du -sh *
-            docker pull fr3akyphantom/droid-builder:focal
-            docker create --name workstation --volume /home/builder/android fr3akyphantom/droid-builder:focal bash
-            for d in *; do
-              /tmp/act.sh & docker cp -a -L ${d} workstation:/home/builder/android/
-              echo -e "${d} is copied in remote"
-            done
-            /tmp/act.sh & docker cp -a -L .repo workstation:/home/builder/android/
-            echo -e "Deleting synced primary files..."
-            /tmp/act.sh & rm -rf *
-            echo -e "Copy and cleanup done"
-            cd /home/builder/
-            echo -en "act-shell pid number is - " && cat /tmp/act.pid
-            ACTPID=$(cat /tmp/act.pid) && kill -s SIGTERM ${ACTPID}
-      - run:
-          name: "REMOTE RECOVERY MAKER"
+          name: "ALL IN REMOTE"
           command: |
             [[ ! -d /home/builder/.ccache ]] && mkdir -p /home/builder/.ccache
             cd /home/builder
@@ -128,25 +60,62 @@ jobs:
             set -eo pipefail
             set
             cd /home/builder/android/
-            sudo chown -Rf builder *
-            sudo ln -sf build/soong/root.bp Android.bp
-            sudo ln -sf build/soong/bootstrap.bash bootstrap.bash
-            ls -lA .
-            # Set GitAuth Infos again"
+            # SANITY CHECKS & GIT SETUP
+            if [[ -z $GitHubMail ]]; then echo -e "You haven't configured GitHub E-Mail Address." && exit 1; fi
+            if [[ -z $GitHubName ]]; then echo -e "You haven't configured GitHub Username." && exit 1; fi
+            if [[ -z $GITHUB_TOKEN ]]; then echo -e "You haven't configured GitHub Token.\nWithout it, recovery can't be published." && exit 1; fi
+            if [[ -z $MANIFEST_BRANCH ]]; then echo -e "You haven't configured PitchBlack Recovery Project Manifest Branch." && exit 1; fi
+            if [[ -z $VENDOR ]]; then echo -e "You haven't configured Vendor name." && exit 1; fi
+            if [[ -z $CODENAME ]]; then echo -e "You haven't configured Device Codename." && exit 1; fi
+            if [[ -z $BUILD_LUNCH ]] && [[ -z $FLAVOR ]]; then echo -e "Set at least one variable. BUILD_LUNCH or FLAVOR." && exit 1; fi
+            # Set GitAuth Infos"
             git config --global user.email $GitHubMail
             git config --global user.name $GitHubName
             git config --global credential.helper store
             git config --global color.ui true
+            # Use Google Git Cookies for Smooth repo-sync
+            git clone -q "https://$GITHUB_TOKEN@github.com/$GitHubName/google-git-cookies.git" &> /dev/null
+            bash google-git-cookies/setup_cookies.sh
+            rm -rf google-git-cookies
+            # threads
+            THREADCOUNT=$(nproc --all)
+            echo -en "Available CPU Threads - " && echo ${THREADCOUNT}
+            if [[ ${THREADCOUNT} -gt 8 ]]; then MAKEJOB=${THREADCOUNT}
+            elif [[ ${THREADCOUNT} -gt 4 && ${THREADCOUNT} -lt 8 ]]; then MAKEJOB=8
+            elif [[ ${THREADCOUNT} -eq 4 ]]; then MAKEJOB=${THREADCOUNT}
+            elif [[ ${THREADCOUNT} -eq 2 ]]; then MAKEJOB=4
+            fi
+            # sync
+            echo -e "Initializing PBRP repo sync..."
+            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
+            /tmp/act.sh & repo sync -c -q --force-sync --no-clone-bundle --no-tags -j${MAKEJOB}
+            # clean unneeded files
+            rm -rf development/apps/ development/samples/ packages/apps/
+            # use pb-10.0
+            rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 --depth 1 vendor/pb
+            rm vendor/pb/vendorsetup.sh
+            if [[ -n ${USE_SECRET_BOOTABLE} ]]; then
+              [[ -n ${PBRP_BRANCH} ]] && unset PBRP_BRANCH
+              [[ -z ${SECRET_BR} ]] && SECRET_BR="android-9.0"
+              rm -rf bootable/recovery
+              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/pbrp_recovery_secrets -b ${SECRET_BR} --single-branch bootable/recovery
+            elif [[ -n ${PBRP_BRANCH} ]]; then
+              rm -rf bootable/recovery
+              git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${PBRP_BRANCH} --single-branch bootable/recovery
+            fi
+            echo -e "\nGetting the Device Tree on place"
+            if [[ "${CIRCLE_PROJECT_USERNAME}" == "PitchBlackRecoveryProject" ]]; then
+              git clone --quiet --progress https://$GitHubName:$GITHUB_TOKEN@github.com/PitchBlackRecoveryProject/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
+            else
+              git clone https://$GITHUB_TOKEN@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${CODENAME}
+            fi
+            ls -lA .
             if [[ -n $EXTRA_CMD ]]; then
               eval "$EXTRA_CMD"
               cd /home/builder/android/
             fi
             JAVA_OPTS=${JAVA_OPTS:+" -Xmx8G "}
             echo -en "Current Username is - " && whoami
-            THREADCOUNT=$(nproc --all)
-            echo -en "Available CPU Threads - " && echo ${THREADCOUNT}
-            echo -e "\nGetting the Device Tree on place"
-            git clone https://$GITHUB_TOKEN@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} --depth 1 device/${VENDOR}/${CODENAME}
             echo -e "\nPreparing Delicious Lunch..."
             export ALLOW_MISSING_DEPENDENCIES=true
             source build/envsetup.sh
@@ -155,33 +124,17 @@ jobs:
             elif [[ -n $FLAVOR ]]; then
               lunch omni_${CODENAME}-${FLAVOR}
             fi
-            if [[ ${THREADCOUNT} -gt 8 ]]; then MAKEJOB=${THREADCOUNT}
-            elif [[ ${THREADCOUNT} -gt 4 && ${THREADCOUNT} -lt 8 ]]; then MAKEJOB=8
-            elif [[ ${THREADCOUNT} -eq 4 ]]; then MAKEJOB=${THREADCOUNT}
-            elif [[ ${THREADCOUNT} -eq 2 ]]; then MAKEJOB=4
-            fi
             make -j${MAKEJOB} recoveryimage
             echo -e "\nYummy Recovery is Served.\n"
-            EOF
-            echo -en "act-shell pid number is - " && cat /tmp/act.pid
-            ACTPID=$(cat /tmp/act.pid) && kill -s SIGTERM ${ACTPID}
-      - run:
-          name: "COPY TO PRIMARY AND RELEASE"
-          command: |
-            cd /home/builder/
-            mkdir fetch && mkdir upload
-            cd /home/builder/fetch/
-            /tmp/act.sh & docker cp -a -L worker:/home/builder/android/out/target/product/${CODENAME}/* .
-            ls -lA .
-            echo "Ready to Deploy"
-            export TEST_BUILDFILE=$(find $(pwd)/PitchBlack*-UNOFFICIAL.zip 2>/dev/null)
-            export TEST_BUILDIMG=$(find $(pwd)/recovery.img 2>/dev/null)
-            cd /home/builder/
-            echo "Got the Unofficial Build: $TEST_BUILDFILE"
-            cp ${TEST_BUILDFILE} ${TEST_BUILDIMG} /home/builder/upload
+            # deploy
+            export TEST_BUILDFILE=$(find $(pwd)/out/target/product/${CODENAME}/PitchBlack*-UNOFFICIAL.zip 2>/dev/null)
+            export TEST_BUILDIMG=$(find $(pwd)/out/target/product/${CODENAME}/recovery.img 2>/dev/null)
+            mkdir upload
+            cp ${TEST_BUILDFILE} ${TEST_BUILDIMG} upload/
             # release
-            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Release for $(echo $CODENAME)" -b "PBRP $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION}-test /home/builder/upload
+            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Release for $(echo $CODENAME)" -b "PBRP $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION}-test upload/
             echo -e "\n\nAll Done Gracefully\n\n"
+            EOF
             echo -en "act-shell pid number is - " && cat /tmp/act.pid
             ACTPID=$(cat /tmp/act.pid) && kill -s SIGTERM ${ACTPID}
 
@@ -192,5 +145,5 @@ workflows:
       - build:
           filters:
             branches:
-              only: "android-10.0"
+              only: "android-10.0-remote"
           context: personal-envs
